# Generated by Django 2.1.1 on 2019-09-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190907_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='picture',
        ),
        migrations.RemoveField(
            model_name='test1_tbl',
            name='stest',
        ),
        migrations.DeleteModel(
            name='test1_tbl',
        ),
        migrations.DeleteModel(
            name='test_tbl',
        ),
    ]
